[package]
name = "kudu"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
description = "Rust client for Apache Kudu"
keywords = ["kudu", "database"]

[workspace]
members = [
  "krpc",
  "krpc-build",
  "krpc-tests",
  "kudu-pb",
]

[dependencies]
byteorder = "1"
chrono = "0.2"
crossbeam = "0.2"
fnv = "1"
futures = "0.1.6"
futures-cpupool = "0.1"
ieee754 = "0.2"
ifaces = "0.0"
itertools = "0.5"
kudu-pb = { path = "kudu-pb", version = "0.1.0" }
lazy_static = "0.2"
log = "0.3"
netbuf = "0.3"
parking_lot = "0.3"
prost = "0.1"
quickcheck = { version = "0.3", optional = true }
rand = "0.3.14"
slab = "0.3"
take_mut = "0.1"
tokio-core = "0.1"
#tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
uuid = "0.3"
vec_map = "0.6"

[dev-dependencies]
tempdir = "0.3"
env_logger = "*"
quickcheck = "0.3"
