[package]
name = "kudu"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
description = "Rust client for Apache Kudu (Incubating)"
keywords = ["kudu", "database"]

[dependencies]
kudu-pb = { path = "kudu-pb", version = "0.1.0" }

[dev-dependencies]
compiletest_rs = "0.1.1"
tempdir = "0.3"
