[package]
name = "kudu"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
description = "Rust client for Apache Kudu (Incubating)"
keywords = ["kudu", "database"]

[dependencies]
kudu-pb = { path = "kudu-pb", version = "0.1.0" }

byteorder = "0.5"
eventual = "0.1.7"
log = "0.3"
mio = "0.5"
netbuf = "0.3"
parking_lot = "0.2"
protobuf = { git = "https://github.com/danburkert/rust-protobuf" }
rand = "0.3.14"
slab = "0.1"
vec_map = "0.6"

[dev-dependencies]
tempdir = "0.3"
env_logger = "*"
