[package]
name = "kudu-pb"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]

[dependencies]
bytes = "0.4"
prost = "0.2"
prost-derive = "0.2"

[build-dependencies]
curl = "0.4"
env_logger = "0.4"
flate2 = "0.2"
prost-build = "0.2"
tar = "0.4"
